# Generated by Django 5.0.1 on 2024-01-15 05:58

import uuid

import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
from django.db import migrations
from django.db import models

import drfpytest.catalog.schemas


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('published', models.BooleanField(default=False)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='catalog.productcategory',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('article', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (
                    'data',
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        exclude_unset=True,
                        schema=drfpytest.catalog.schemas.ProductData,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='products',
                        to='catalog.productcategory',
                    ),
                ),
            ],
            options={
                'indexes': [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=['data'], name='catalog_pro_data_683a16_gin'
                    )
                ],
            },
        ),
    ]
